3.3
Svelte-Society-Fr/learn.svelte.dev pull request #15
Opened 2023-08-17 07:37 UTC by iOiurson

2023-08-19 07:44 UTC, Ennoriel requested changes

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/03-loading-data/01-page-data/README.md
> +> Dans le cadre de ce tutoriel, nous importons la donnée depuis `src/routes/blog/data.js`. Dans une vrai application, vous chargeriez plutôt cette donnée depuis une base de données ou un CMS, mais po
```suggestion
> Dans le cadre de ce tutoriel, nous importons la donnée depuis `src/routes/blog/data.js`. Dans une vraie application, vous chargeriez plutôt cette donnée depuis une base de données ou un CMS, mais pour le moment nous le faisons de cette manière.
```

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/03-loading-data/01-page-data/app-a/src/routes/blog/data.js
> +			"<p>Bien que la sécurité est un des nombreux objectifs du centre d'enrichissement, la Pilule Haute Énergie d'Aperture Science, à droite de la chambre, peut et a déjà causé des handicaps permanents
```suggestion
			"<p>Bien que la sécurité soit un des nombreux objectifs du centre d'enrichissement, la Pilule Haute Énergie d'Aperture Science, à droite de la chambre, peut et a déjà causé des handicaps permanents, comme la vaporisation. Agissez avec prudence.</p>"
```

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/03-loading-data/02-layout-data/README.md
> +De la même manière que les fichiers `+layout.svelte` crée de l'interface pour chaque route enfant, les fichiers `+layout.server.js` chargent de la donnée pour chaque route enfant.
```suggestion
De la même manière que les fichiers `+layout.svelte` crée une partie de l'interface pour chaque route enfant, les fichiers `+layout.server.js` chargent de la donnée pour chaque route enfant.
```

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/04-headers-and-cookies/02-cookies/README.md
> +Appeler `cookies.set(name, ...)` implique que le <span class="vo">[header](SVELTE_SITE_URL/docs/web#header)</span> `Set-Cookie` est modifié, mais cela met _également_ à jour le dictionnaire interne d
```suggestion
Appeler `cookies.set(name, ...)` implique que le <span class="vo">[header](SVELTE_SITE_URL/docs/web#header)</span> `Set-Cookie` soit modifié, mais cela met _également_ à jour le dictionnaire interne de cookies, signifiant que les appels suivants à `cookies.get(name)` durant la même requête renverront la valeur à jour. Sous le capot, l'<span class="vo">[API](SVELTE_SITE_URL/docs/development#api)</span> `cookies` utilise la libraire populaire `cookie` — les options passées à `cookies.get` et `cookies.set` correspondent aux options de `parse` et `serialize` définies dans la [documentation de la libraire `cookie`](https://github.com/jshttp/cookie#api). SvelteKit utilise les valeurs par défaut suivantes pour rendre vos cookies plus sécurisés :
```

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +Dans le [chapitre sur le chargement](page-data), nous avons vu comment charger de la donnée depuis le serveur vers le navigateur. Parfois, il est nécessaire d'envoyer de la donnée dans l'autre direct
```suggestion
Dans le [chapitre sur le chargement](page-data), nous avons vu comment charger de la donnée depuis le serveur vers le navigateur. Parfois, il est nécessaire d'envoyer de la donnée dans l'autre direction, et c'est là que les éléments de formulaires `<form>` — la méthode standard du web pour soumettre de la donnée — entrent en jeu.
```

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/06-forms/01-the-form-element/README.md
> +Si nous entrons quelque dans l'`<input>` et que nous appuyons sur Entrée, le navigateur fait une requête POST (grâce à l'attribut `method="POST"`) sur la page actuelle. Mais cela renvoie une erreur,
```suggestion
Si nous saisissons quelque chose dans l'`<input>` et que nous appuyons sur Entrée, le navigateur fait une requête POST (grâce à l'attribut `method="POST"`) sur la page actuelle. Mais cela renvoie une erreur, car nous n'avons pas créé d'_action_ côté serveur pour gérer la requête POST. Faisons cela maintenant :
```

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/07-api-routes/01-get-handlers/README.md
> +SvelteKit vous permet de créer plus que juste des pages. Nous pouvons aussi créer des _routes d'<span class="vo">[API](SVELTE_SITE_URL/docs/development#api)</span>_ en ajoutant un fichier `+server.js
```suggestion
SvelteKit vous permet de créer plus que des simples pages. Nous pouvons aussi créer des _routes d'<span class="vo">[API](SVELTE_SITE_URL/docs/development#api)</span>_ en ajoutant un fichier `+server.js` qui exporte des fonctions correspondant aux méthodes HTTP : `GET`, `PUT`, `POST`, `PATCH`, `DELETE`.
```

2023-08-19 07:44 UTC, Ennoriel commented on content/tutorial/03-sveltekit/07-api-routes/01-get-handlers/README.md
> +Les gestionnaires de requêtes doivent renvoyer un objet [Response](https://developer.mozilla.org/fr/docs/Web/API/Response/Response). Puisqu'il est courant de renvoyer du <span class="vo">[JSON](SVELT
```suggestion
Les gestionnaires de requêtes doivent renvoyer un objet [Response](https://developer.mozilla.org/fr/docs/Web/API/Response/Response). Puisqu'il est courant de renvoyer du <span class="vo">[Json](SVELTE_SITE_URL/docs/web#json)</span> depuis une route d'<span class="vo">[API](SVELTE_SITE_URL/docs/development#api)</span>, SvelteKit fournit une fonction utilitaire pour générer de telles réponses :
```

2023-08-20 13:47 UTC, iOiurson commented on content/tutorial/03-sveltekit/03-loading-data/01-page-data/app-a/src/routes/blog/data.js
> +			"<p>Bien que la sécurité est un des nombreux objectifs du centre d'enrichissement, la Pilule Haute Énergie d'Aperture Science, à droite de la chambre, peut et a déjà causé des handicaps permanents
"bien que" est suivi du subjonctif

2023-08-20 13:48 UTC, iOiurson commented on content/tutorial/03-sveltekit/04-headers-and-cookies/02-cookies/README.md
> +Appeler `cookies.set(name, ...)` implique que le <span class="vo">[header](SVELTE_SITE_URL/docs/web#header)</span> `Set-Cookie` est modifié, mais cela met _également_ à jour le dictionnaire interne d
En revanche ici je ne pense pas que le subjonctif soit de mise.

2023-08-20 13:50 UTC, iOiurson commented on content/tutorial/03-sveltekit/07-api-routes/01-get-handlers/README.md
> +Les gestionnaires de requêtes doivent renvoyer un objet [Response](https://developer.mozilla.org/fr/docs/Web/API/Response/Response). Puisqu'il est courant de renvoyer du <span class="vo">[JSON](SVELT
"JSON" c'est un acronyme.

2023-08-20 13:53 UTC, Ennoriel commented on content/tutorial/03-sveltekit/04-headers-and-cookies/02-cookies/README.md
> +Appeler `cookies.set(name, ...)` implique que le <span class="vo">[header](SVELTE_SITE_URL/docs/web#header)</span> `Set-Cookie` est modifié, mais cela met _également_ à jour le dictionnaire interne d
https://dictionnaire.lerobert.com/guide/proposition-subordonnee > Circonstancielle de but ? de conséquence ?

2023-08-20 13:58 UTC, iOiurson commented on content/tutorial/03-sveltekit/04-headers-and-cookies/02-cookies/README.md
> +Appeler `cookies.set(name, ...)` implique que le <span class="vo">[header](SVELTE_SITE_URL/docs/web#header)</span> `Set-Cookie` est modifié, mais cela met _également_ à jour le dictionnaire interne d
Concession https://fr.wiktionary.org/wiki/bien_que

2023-08-20 14:01 UTC, iOiurson commented on content/tutorial/03-sveltekit/04-headers-and-cookies/02-cookies/README.md
> +Appeler `cookies.set(name, ...)` implique que le <span class="vo">[header](SVELTE_SITE_URL/docs/web#header)</span> `Set-Cookie` est modifié, mais cela met _également_ à jour le dictionnaire interne d
chai pas, mais cette phrase décrit un fait, pour moi ça doit être de l'indicatif

2023-08-20 15:50 UTC, merged